### ISSUE TITLE
最终生成的文件相比mentohust-proxy的要大个几十k

### ISSUE THREAD

**Issue by Droid-MAX** [updateing/mentohust-v4-proxy#2]
这是因为使用的v4版本算法的缘故吗？

**Comment by updateing** [comment]
两个数组加三个抓包，纯数据都得有7KB左右了，新的校验算法里还有一大堆常数……大这么多也比较正常吧。

**Comment by updateing** [comment]
……手机上误触close了，需要的话可以reopen 😂

**Comment by Droid-MAX** [comment]
怎么reopen呀。。😂

**Comment by Droid-MAX** [comment]
你在用这个邮箱吗？mentohust@ehust.co.cc

**Comment by updateing** [comment]
这个邮箱地址对应的作者名称肯定不是我 [doge]

作者名称是 Hamster Tian 的commit才是我提交的。

**Comment by Droid-MAX** [comment]
http://pan.baidu.com/share/link?shareid=1152643283&uk=3294023664
你们那边也存留一份吧，看有没有需要的人，虽然我搞这些只是业余的2333

**Comment by Droid-MAX** [comment]
那我折腾这些东西就告一段落了，后会有期~

**Comment by updateing** [comment]
谢谢，再会~
