### ISSUE TITLE
关于交叉编译的问题

### ISSUE THREAD

**Issue by CCRRREAL** [updateing/mentohust-v4-proxy#8]
大佬您好！
我在ubuntu18.04下参照[从零开始配置支持锐捷认证与IPv6的路由器](https://www.jianshu.com/p/54fed2933271)这里的交叉编译的教程编译，使用了[openwrt18.06的SDK](https://downloads.openwrt.org/releases/18.06.4/targets/ramips/mt7620/openwrt-sdk-18.06.4-ramips-mt7620_gcc-7.3.0_musl.Linux-x86_64.tar.xz)进行编译,make之后出现了以下的问题
![问题](https://s2.ax1x.com/2019/09/09/nJ7y3d.png)
其中我分别尝试链接了1.7.4   1.8.1   1.9.0的libpcap.a也无济于事
我又试了试原版的V4验证的mentohust，是可以编译成功的
所以大佬您能看看这是出了啥问题了🐎
谢谢！

**Comment by ephphpff** [comment]
你好请问问题解决了么？

**Comment by CCRRREAL** [comment]
> 问题解决了么？

其实没解决，感觉是op的SDK没链接到对应的库？我后来转去编译minieap了，没什么问题，就没去管了:-)
